---
title: Qwentes template

timezone: UTC

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@qwentes.it

exclude:
  - node_modules
  - gulp
  - Gemfile.old
  - Gemfile.lock.old
  - gulpfile.js
  - package.json
  - config.rb
  - README.md
  - webpack.config.js
  - LICENSE


github_username: jekyll

markdown: kramdown

sass:
  style: extended

